nelmio_cors:
    defaults:
        allow_origin: ['*']
        allow_methods: ['GET', 'POST', 'PUT', 'DELETE']
        allow_headers: ['*']
        max_age: 3600
    paths:
        '^/': 
            allow_origin: ['http://localhost:4200']
            allow_headers: ['*']
            allow_methods: ['GET', 'OPTIONS', 'POST', 'PUT', 'DELETE']
            max_age: 3600
