controllers:
        resource: ../src/Controller/
        type: attribute
app_is_empreinte_in_range:
    path: '/isEmpreinteInRange'
    controller: 'App\Controller\YourController::isEmpreinteInRange'
    methods: ['POST']
    